version: "3.9"
services:
  crossshare_server:
    build: .
    restart: always
    ports:
      - "3007:3007"
    # environment:
    #   ALIDDNS_LOG_LEVEL: info
    volumes:
      - ./cmd/crossshare_server/config.toml:/usr/local/bin/config.toml
    networks:
      - eagle
  
  # sudo sysctl vm.overcommit_memory=1 
  redis:
    image: redis:7-alpine
    restart: always
    # ports:
    #   - 6378:6379


networks:
  eagle:
    name: eagle
    external: true